/// Generated by AssetsRefGenerator on 2020/12/19
class Res {
  static const String alpagaBaseLogo = "images/alpagaBaseLogo.png";
  static const String twitchLogoButton = "images/twitchLogoButton.png";

}

