/// Generated by AssetsRefGenerator on 2020/12/14
class Res {
  static const String alpagaBaseLogo = "images/alpagaBaseLogo.png";
}

class ResFont {
  static const String fascinate = 'Fascinate';
  static const String openSans = 'OpenSans';

}
